### ISSUE TITLE
Question: Does libonnx support dynamic shape/CUDA ?

### ISSUE THREAD

**Issue by delldu** [xboot/libonnx#14]
Dear friends,
    Thanks for good job.
    We have two question:  1) Does libonnx support dynamic shape input ? If not, how to implement it ? (Just some hints.);
    2) How to support CUDA inference on libonnx ?

**Comment by jianjunjiang** [comment]
see struct onnx_tensor_t, this can expressd for any data type, CUDA  inference, you must write a struct onnx_resolver_t, this is a iterface for some hardware acceleration

**Comment by delldu** [comment]
@jianjunjiang ,Thank you.  We also wonder how support dynamic input shape with libonnx ? Would you please give us some advance ?

**Comment by jianjunjiang** [comment]
[https://github.com/xboot/libonnx/blob/8f6c6a02a28d330b5c640856664a5cf835dfdb7c/examples/hello/main.c#L2272](url)

using onnx_tensor_apply function to modify input tensor

**Comment by delldu** [comment]
Many thanks.
