### ISSUE TITLE
Why does every test in the model, node and simple folders fail?

### ISSUE THREAD

**Issue by abhinandanudupa** [xboot/libonnx#16]
I have compiled `libonnx` on a fresh installation of Ubuntu - installed all the prerequisites ran just `make` and tried running the tests one by one. But I find the every test that I run fails and I am not able to figure out why.

Here is what I did:
- Installed the latest LTS release of Ubuntu
- Installed make, build-essential, git and libsdl2-gfx (Did do other stuff but those would not mess with this)
- Ran `make all` to compile
- Ran the tests on many examples: `./tests ./model/mnist_8/`
- But every test that I have tried has just failed!
```bash
$ ./TESTING/libonnx/tests/tests ./TESTING/libonnx/tests/model/mnist_8/
[test_data_set_0]                                                                       [FAIL]
[test_data_set_1]                                                                       [FAIL]
[test_data_set_2]                                                                       [FAIL]
```
- All those in the simple and model folders fail but those in pytorch-* succeed partially
- Is this because of a missing operator? (no `Unsupported opset` message has been displayed as in the pytorch tests)
- Nonetheless the example for handwriting recognition has identified the number correctly most of the time

**Comment by abhinandanudupa** [comment]
**Update:**
Running `./libonnx/tests/tests ./libonnx/tests/model/$(wildcard *)` will give the required output:
```bash
wildcard: command not found
[mnist_8](test_data_set_0)                                                              [OKAY]
[mnist_8](test_data_set_1)                                                              [OKAY]
[mnist_8](test_data_set_2)                                                              [OKAY]
[mobilenet_v2_7](test_data_set_0)                                                       [OKAY]
[mobilenet_v2_7](test_data_set_1)                                                       [OKAY]
[mobilenet_v2_7](test_data_set_2)                                                       [OKAY]
[shufflenet_v1_9](test_data_set_0)                                                      [OKAY]
[shufflenet_v1_9](test_data_set_1)                                                      [OKAY]
[shufflenet_v1_9](test_data_set_2)                                                      [OKAY]
[squeezenet_v11_7](test_data_set_0)                                                     [OKAY]
[squeezenet_v11_7](test_data_set_1)                                                     [OKAY]
[squeezenet_v11_7](test_data_set_2)                                                     [OKAY]
[super_resolution_10](test_data_set_0)                                                  [OKAY]
[tinyyolo_v2_8](test_data_set_0)                                                        [OKAY]
[tinyyolo_v2_8](test_data_set_1)                                                        [OKAY]
[tinyyolo_v2_8](test_data_set_2)                                                        [OKAY]
```
Why is this so?
Can you explain?

**Comment by abhinandanudupa** [comment]
Also in the `mnsit_8` test what are the `input_0.pb` and similar files?
Are they the images in `Protocol Buffer file format` and if so then how do I convert my image to a `.pb` file?

**Comment by jianjunjiang** [comment]
`usage:
    tests <DIRECTORY>
examples:
    tests ./tests/model
    tests ./tests/node
    tests ./tests/pytorch-converted
    tests ./tests/pytorch-operator
    tests ./tests/simple
`

**Comment by abhinandanudupa** [comment]
> **Update:**
> Running `./libonnx/tests/tests ./libonnx/tests/model/$(wildcard *)` will give the required output:
> 
> ```shell
> wildcard: command not found
> [mnist_8](test_data_set_0)                                                              [OKAY]
> [mnist_8](test_data_set_1)                                                              [OKAY]
> [mnist_8](test_data_set_2)                                                              [OKAY]
> [mobilenet_v2_7](test_data_set_0)                                                       [OKAY]
> [mobilenet_v2_7](test_data_set_1)                                                       [OKAY]
> [mobilenet_v2_7](test_data_set_2)                                                       [OKAY]
> [shufflenet_v1_9](test_data_set_0)                                                      [OKAY]
> [shufflenet_v1_9](test_data_set_1)                                                      [OKAY]
> [shufflenet_v1_9](test_data_set_2)                                                      [OKAY]
> [squeezenet_v11_7](test_data_set_0)                                                     [OKAY]
> [squeezenet_v11_7](test_data_set_1)                                                     [OKAY]
> [squeezenet_v11_7](test_data_set_2)                                                     [OKAY]
> [super_resolution_10](test_data_set_0)                                                  [OKAY]
> [tinyyolo_v2_8](test_data_set_0)                                                        [OKAY]
> [tinyyolo_v2_8](test_data_set_1)                                                        [OKAY]
> [tinyyolo_v2_8](test_data_set_2)                                                        [OKAY]
> ```
> 
> Why is this so?
> Can you explain?

Little did I realise that `wildcard` was a `make` function and not a `bash` function.
