### ISSUE TITLE
isnan and isinf issue

### ISSUE THREAD

**Issue by noomio** [xboot/libonnx#2]
Hi,

When I compile I get the following error with clang. I then try to link the library and it complains. Not quite sure why, I added in the main.c isnan and isinf and compiles ok. -lm is added to the linker.

Library compilation:
`
default/IsNaN.c:34:11: warning: implicit declaration of function 'isnanf' is invalid in C99
      [-Wimplicit-function-declaration]
                py[i] = isnanf(v) ? 1 : 0;
`

Linker:
`libonnx.a(.text+0x598): undefined reference to isnanf'`

**Comment by noomio** [comment]
Oh its a float check.
I added this to my main build:
#define isinff isinf
#define isnanf isnan

The math checks the type already.

**Comment by jianjunjiang** [comment]
yes, you are right, isinff and isnanf are alias to isinf and isnan, following commit patched it.
https://github.com/xboot/libonnx/commit/5ab486d7b196b621d6ef04f3a63f1261b466d103
