### ISSUE TITLE
Can this software run on MacOS

### ISSUE THREAD

**Issue by feifeibear** [xboot/libonnx#7]
I came across an error when compling it on my Mac.

[CC] helper.c
In file included from helper.c:28:
./helper.h:13:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~
1 error generated.
make[1]: *** [helper.o] Error 1
make: *** [all] Error 2

**Comment by jianjunjiang** [comment]
macos don‘t have malloc.h ? this is c startard library.

**Comment by feifeibear** [comment]
https://stackoverflow.com/questions/56463049/should-mac-osx-have-a-malloc-h-file

According to this post, it is not a standard one any more.

**Comment by jianjunjiang** [comment]
just remove malloc.h, and compile it will be ok.
if memalign fail, using malloc instead
