### ISSUE TITLE
This project need SDL2.

### ISSUE THREAD

**Issue by wuzy361** [xboot/libonnx#8]
At first , I got error when complie this project:
 main.c:1:10: fatal error: SDL2/SDL.h: 没有那个文件或目录
    1 | #include <SDL2/SDL.h>
      |          ^~~~~~~~~~~~
then I use `sudo apt-get install libsdl2-gfx-dev` fixed this error.

I think this project should explain this dependence.

THANKS!

**Comment by ouankou** [comment]
I encountered the same issue. On Arch/Manjaro Linux, it's `yay -Syu sdl2_gfx`.

**Comment by LeeeSe** [comment]
Thank you !~
